#
# Jekyll configuration
#

title: Bob Fanger's website
email: bfanger@gmail.com
description: Software in Style
baseurl: ""
url: http://bfanger.nl/
twitter_username: bfanger
github_username:  bfanger

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - composer.json
  - composer.lock
  - vendor

collections:
  projects:
    output: true
  experiments:
    output: true

defaults: 
  - scope: 
      type: projects
    values:
      layout: project 

sass:
  style: compressed